Cargo.toml, src/error.rs, src/lib.rs, tests/ping_pong.rs
These exercise the public API in a more realistic (but admittedly still quite simplistic) way than the unit tests.
Since they must use the public API we notice that `Poll`, `Error` and `Result` were private which made it hard to consume the API.
=> Add some simple integration tests

.github/workflows/ci.yaml, .github/workflows/nightly-cargo-deny.yaml, Earthfile, deny.toml
**Changes:**
- Add deny.toml which `cargo-deny` uses to check license
- Add earthly target `check-license` for checking licenses
- Update github actions to run this target on all PRs
=> Add cargo deny to audit licenses of dependencies

src/context.rs
Previously 6bc441700598 ("Mark `NonNull<wolfssl_sys::WOLFSSL>` and
`WOLFSSL_CTX` as`Send`") noted that we went further than required by WolfSSL in
our use of a `Mutex` here.
However 84af20b29214 ("Remove `Mutex` from around `Context::ctx`") then
immediately removed that `Mutex`, resulting in `Context` no longer being
`Sync`!
Per the WolfSSL documentation it appears to be safe to use a
`wolfssl_sys::WOLFSSL_CTX` from multiple threads so long as it is used
read-only. We already have protections in place to ensure this.
=> Implement `Sync` on `ContextPointer` (so `Context` becomes `Sync`)

.github/workflows/ci.yaml, Earthfile
[example failed run](https://github.com/expressvpn/wolfssl/actions/runs/6157850304/job/16709457229?pr=26).
=>  CI: Run `cargo fmt` in CI, fail if things differ

.github/workflows/ci.yaml
Added a new github meta job which depends on all other jobs
Currently we need to specify all the required jobs in CI workflow as required checks in branch protection rule.
Having a meta job which depends on all other jobs reduce this dependency.
And we can use this meta job as required checks in branch protection rules.
=> Add github meta job which depends on all jobs

src/context.rs, src/ssl.rs
This allows a bit better error reporting than returning an `Option`. I think mainly useful in practice for `Session` in the case where one of the post-creation setup methods fails, WolfSSL doesn't give us any hint why the actual creates fail.
=> Use specific errors when creating a `ContextBuilder` or a `Session` fails

src/context.rs, src/error.rs, src/lib.rs, src/rng.rs, src/ssl.rs
**Code changes:**
- Enable clippy undocumented_unsafe_blocks lint in CI
- As first step, add `#[allow(undocumented_unsafe_blocks)]` for all unsafe code
- Added safety comments for following files:
- lib.rs
- context.rs
- error.rs
- rng.rs
-  ssl.rs
**Note:**
There are two block left without SAFETY comments in `wolf_init` and `wolf_cleanup`   for now
Will fix up in followup pr
=> Enable clippy undocumented_unsafe_blocks lint

src/context.rs, src/error.rs, src/lib.rs, src/rng.rs
As discussed in https://github.com/expressvpn/wolfssl/pull/24#discussion_r1322705812 https://github.com/expressvpn/wolfssl/pull/24#discussion_r1322685417 these put safety were putting safety requirements into the responsibility of the caller.
For `wolf_init` push the responsibility for calling this into this crate so we can be sure we meet the "before any other call to the library" requirement from [the documentation](https://www.wolfssl.com/doxygen/group__TLS.html#ga789ef74e34df659a62f06da2ea709737). The places where we need to do the initialization are few in number and none are in hot paths -- I think it unlikely that there would ever be a hot path which didn't require some cold path setup first so I think we aren't making a rod for our own back by taking on this responsibility, …
=> Remove `wolf_init` from public view and remove `wolf_cleanup` entirely

.github/workflows/nightly-rust-update-check.yaml
A nightly GHA which checks for a new version of Rust and raises a PR updating Earthfile if needed.
Note that Rust releases roughly every 6 weeks, with occasional point releases, so ~41/42 times the GHA will be a NOP
Lets review/merge https://github.com/expressvpn/wolfssl-sys/pull/49 first to validate then this one is identical.
=> GHA: Check nightly for new Rust toolchain and raise a PR

src/ssl.rs
... useful for applications which wish to update some state in their adapter without going for `Arc` etc to retain a handle.
The `IOCB` is exposed to FFI since it is used as the WolfSSL IO callback target. Therefore it is worth thinking about the safety constrains a little even though there is no `unsafe` here, particularly around `io_cb_mut`: WolfSSL is completely inert unless application code calls into it (i.e. it has no threads etc of its own). So the only way any C code can be active (and therefore potentially accessing the `IOCB` type) is if something is currently calling one of the methods on the `Sesssion` object. Since `io_cb_mut` takes a `&mut self` we therefore know that no other thread can be calling through to C code while such a reference is live, therefore it is safe to …
=> Allow access to the `IOCB` within a `Session<IOCB>`

src/context.rs
`Error::fatal` does a fair bit of work, including calling `wolf_error_string` to stringify the error (which allocates), lets not do that until an error has actually happened.
Noticed when setting a breakpoint on `Error::fatal` which then triggered frequently.
=> Do not construct `Error` values unless needed.

.github/workflows/ci.yaml, Earthfile, README.md
This PR reduces GH actions build time from around 8m to 50s for the most likely scenario of only source code changing.
It takes @idelvall's changes from https://github.com/expressvpn/wolfssl-rs/pull/23 and rebases it onto the latest master with some cosmetic changes.
To do once this PR is approved:
=> LIT-122: Speed up builds using Earthly Satellite

.github/workflows/ci.yaml
A last minute change to 4f081570d31a ("GHA: Run coverage during CI") changed the comment message (to add a link) such that `peter-evans/find-comment@v2` no longer matched the body text.
=> GHA: Ensure coverage job updates a single comment

.github/workflows/ci.yaml, Earthfile
Conservative values based on our current coverage on #44 (most recently merged to main) which has regions at 54% and lines at 72%.
Tested by temporarily pushing some stricter thresholds. 4bb8172 ([logs](https://github.com/expressvpn/wolfssl-rs/actions/runs/6351440645/job/17252676204?pr=47)) fails a hard threshold and 3673602 ([logs](https://github.com/expressvpn/wolfssl-rs/actions/runs/6351457862/job/17252718261?pr=47)) fails a soft one. You can find the results in the previous edits of the comment from the bot below.
=> GHA: Enforce some limits on code coverage

.github/workflows/ci.yaml, Earthfile, README.md
Here's what it looks like!
```
$ earthly doc
TARGETS:
+build-dev
build-dev builds with the Cargo dev profile and produces debug artifacts
+build-release
build-release builds with the Cargo release profile and produces release artifacts
+run-tests
run-tests executes all unit and integration tests via Cargo
+run-coverage
run-coverage generates a report of code coverage by unit and integration tests
+build
build runs tests and then creates a release build
+lint
lint runs cargo clippy on the ssource code
+fmt
fmt formats Rust code according to style guidelines
+check-dependencies
check-dependencies lints our dependencies
```
=> LIT-122: Add support for `earthly doc`

.github/workflows/ci.yaml, Earthfile
This PR:
- Upgrades the version of earthly to 0.7.20
- Uses the a new UDC version that removes the usage of CACHEs in favor of mount caches, for better performance when the cache size grows.
=> upgrade earthly and cargo UDC

Cargo.lock, wolfssl-sys/Cargo.toml
https://github.com/rust-lang/rust-bindgen/compare/v0.65.1...v0.68.1
---
https://github.com/expressvpn/wolfssl-rs/actions/runs/6401913884/job/17377704752 was the weekly job which failed to highlight this, it actually failed for a couple of weeks.
Interesting bit of the upstream diff might be the changelog diff: https://github.com/rust-lang/rust-bindgen/compare/v0.65.1...v0.68.1#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR191
<details>
<summary>The actual changes to generated `bindings.rs` are pretty dull</summary>
```diff
--- ./target/debug/build/wolfssl-sys-5299f67980159668/out/bindings.rs	2023-10-06 10:13:20.597765791 +0100
+++ /home/ianc/Development/lightway/orga-expressvpn/wolfssl-rs/./target/debug/build/wolfssl-sys-fcda466f0ea2d668/out/bindings.rs	2023-10-09 …
```
=> wolfssl-sys: Bump to bindgen 0.68.1

deny.toml
In 18884738310d ("wolfssl-sys: update liboqs to 0.8.0") we switched back to a released version.
=> deny.toml: Remove `allow-git` for liboqs

Earthfile, deny.toml
The `cargo deny` check was passing but generating lots of warnings, one was fixed by #54, this addresses the remainder (which are due to duplicate versions) and then causes all warnings from `cargo deny` to become fatal in CI so we should catch any new ones.
=> Make `cargo deny`  warnings fatal

Earthfile
`cargo` uses timestamps to decide when to rebuild things so it is important that they are reflected within the build container environment.
=> Earthfile: Preserve timestamps on source code

.github/workflows/ci.yaml, Earthfile
- Bumping to https://github.com/earthly/lib/compare/2.2.4...2.2.5 allow us to use `--keep_fingerprints=true` since after 45423285950 this workaround is not needed.
- Bumping to https://github.com/earthly/lib/compare/2.2.5...2.2.6 keeps us up to date, but since we do not use `--output` doesn't affect us here.
- Use the UDC to install `cargo-deny` and `cargo-llvm-cov` so we will cache things
- Use a matrix job for the simple "just run Earthly target" cases, less repetition
=> Update to new Earthly UDC

.github/workflows/ci.yaml
There was a lot of noise in the PRs due to the environment secret usuage. Everytime we made a change in the PR, the PR is flooded with
`deployed to environment...`
messages.
So we moved the secrets from environment to repo level. This commit removes the environment value from ci so that github actions will use repo secrets.
=> ci: use repo secrets instead of environment secrets

Earthfile
... not whatever happens to be in the `target/` cache when we run `llvm-cov report`.
There are two parts of this, first we must specify the coverage target directory as outputs so `rust-udc+CARGO` will propagate them from the target cache mount to the local target. Second we must not use the target cache when we generate the reports.
The full `target/llvm-cov-target` does appear to be needed to generate the reports.
=> Earthfile: Generate coverage results from actual rusts

.github/workflows/ci.yaml, Earthfile
=> Update Earthly to v0.7.21 and UDC to v2.2.7

wolfssl/src/lib.rs, wolfssl/src/ssl.rs
Although the [documentation] talks about "TLS 1.3" this feature is available for DTLS 1.3 too (confirmed in the code).
[documentation]: https://www.wolfssl.com/documentation/manuals/wolfssl/group__IO.html#function-wolfssl_update_keys
=> wolfssl: Allow key rotation for DTLS 1.3 connections

wolfssl/src/context.rs, wolfssl/src/ssl.rs
This simplifies:
```rust
let wolfssl = wolfssl::ContextBuilder::new(protocol)?
.with_root_certificate(root_ca)?
.with_cipher_list(Cipher::default().as_cipher_list(connection_type))?;
let wolfssl = if connection_type.is_datagram() {
wolfssl.with_secure_renegotiation()?
} else {
wolfssl
};
```
into
```rust
let wolfssl = wolfssl::ContextBuilder::new(protocol)?
.with_root_certificate(root_ca)?
.with_cipher_list(Cipher::default().as_cipher_list(connection_type))?
.try_when(connection_type.is_datagram(), |s| s.with_dtls_nonblocking(true))?;
```
or
```rust
let wolfssl = wolfssl::ContextBuilder::new(protocol)?
.with_private_key(server_key)?
.with_certificate(server_cert)?
.with_groups(SERVER_CURVE_BASE_GROUPS)?;
let wolfssl = if connection_type.is_datagram() { …
```
=> Add some predicate helpers to `ContextBuilder` and `SessionConfig`

.github/workflows/ci.yaml, Earthfile, deny.toml, wolfssl-sys/build.rs
Cancel all but the latest job for PR (non-main) branches.
Use the new UDC which includes a `set -e` fix and allows us to avoid `--output` on the coverage job (which copies several GB of data around)
=> GHA and Earthly updates

Earthfile, wolfssl-sys/build.rs, wolfssl/src/debug.rs, wolfssl/src/lib.rs, wolfssl/src/ssl.rs, wolfssl/tests/ping_pong.rs
WolfSSL provides  a way to dump secrets in TLS13 which can be used to decrypt traffic using Wireshark.
Ref: 
https://github.com/wolfSSL/wolfssl-examples/blob/master/tls/server-tls13.c 
https://github.com/wolfSSL/wolfssl-examples/blob/master/tls/client-tls13.c 
This PR adds helpers in wolfssl-rs to support that feature
=> LIT-193: New trait for receiving TLS1.3 secrets in debug mode

.github/workflows/nightly-rust-update-check.yaml
Add link to changelog in PR body.
Official rust changelog is a single page with URL having release date too. https://doc.rust-lang.org/nightly/releases.html#version-1750-2023-12-28
Easier to use `releases.rs` to point to specific version changelog, since it does not have release date in URLs.
=> GHA: add changelog while updating rust version

wolfssl-sys/build.rs
I initially just wanted to add the missing `cargo:rerun-if-changed` since it has been bugging me during debugging sessions where I was modifying wolfssl C code.
But then I realized that the variable naming for the paths was a bit confusing and that had led to us using paths which were "logically" "wrong" -- things worked since the `$OUT_DIR` and where we install the C wolfssl bits happened to overlap but it meant we were rather inconsistent in how we referred to various paths.
Converting all path stuff to use `std::path` means we can use the helpers (`join` etc) and improved portability, but also I suspect that some of the reason we were using the "wrong" path for things semantically was due to it being more convenient to use a handy `&str` which happened to point to the right place than …
=> wolfssl-sys: rebuild if c source changed & fixup path conventions in build.rs

Cargo.lock
Fixing error:
```
error[vulnerability]: Multiple issues involving quote API
┌─ /work/expressvpn/wolfssl-rs/Cargo.lock:59:1
│
59 │ shlex 1.2.0 registry+https://github.com/rust-lang/crates.io-index
│ ----------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2024-0006
= Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0006
= ## Issue 1: Failure to quote characters
```
Found in nightly cargo deny job:
https://github.com/expressvpn/wolfssl-rs/actions/runs/7611230071
=> cargo: update shlex vulnerable dependency

.github/workflows/weekly-cargo-update.yaml
instead of Wednesday.
This makes it easier to find issues earlier in week if any.
=> ci: run weekly cargo update on monday

.github/workflows/ci.yaml, Earthfile
`--global-cache` is the default in this version.
=> Update to Earthly 0.8.3

.github/workflows/ci.yaml, .github/workflows/nightly-cargo-deny.yaml, .github/workflows/nightly-rust-update-check.yaml, .github/workflows/weekly-cargo-update.yaml
This addresses the node16 to node20 transition:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20
=> GHA: Bump actions to latest versions

wolfssl/src/error.rs
On linux/arm64 when building binaries, there is an error saying the arguments to the function `wolfssl_sys::wolfSSL_ERR_error_string` are incorrect. Further notes by the compiler:
> expected raw pointer `*mut u8`
>    found raw pointer `*mut i8`
Since the code in error was generated by rust-bindgen, it could be that rust-bindgen is generating architecture specific code. According to rust docs, the C Char type could be i8 or u8, depending on architecture.
https://doc.rust-lang.org/core/ffi/type.c_char.html
Which makes sense when this error only shows up on the linux/arm64 platform.
The fix is to replace the hardcoded u8/i8 with `std::os::raw::c_char`, and let the compiler decide the type to use at compile time.
=> CVPN-525 Fix C Char Type Mismatch Error on linux/arm64

wolfssl-sys/Cargo.toml
This removes the warning:
```
warning: wolfssl-rs/wolfssl-sys/Cargo.toml: version requirement `0.9.1+liboqs-0.9.0` for dependency `oqs-sys` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
```
Since the metadata is ignored there is no change to `Cargo.lock` or to what is actually built.
Note that this is ommitted in e.g. https://crates.io/crates/oqs-sys and would be omitted by `cargo add -p wolfssl-sys oqs-sys` too.
=> wolfssl-sys: Omit semver metadata from oqs-sys dependency.

Cargo.lock
update windows-targets to 0.52.4 from yanked 0.52.3 version.
Fixing:
https://github.com/expressvpn/wolfssl-rs/actions/runs/8096083254/job/22124160646
Error:
```
error[yanked]: detected yanked crate (try `cargo update -p windows-targets`)
┌─ /work/expressvpn/wolfssl-rs/Cargo.lock:83:1
│
219 │ windows-targets 0.52.3 registry+https://github.com/rust-lang/crates.io-index
│ ---------------------------------------------------------------------------- yanked version
│
```
=> cargo-deny: update windows-targets to 0.52.4

deny.toml
Several fields were deprecated and causing warnings, out settings match the new default behaviour anyway.
See https://github.com/EmbarkStudios/cargo-deny/pull/611 for more.
=> deny.toml: Update for advisories and licenses stanzas to version 2

Earthfile
https://github.com/earthly/lib/compare/2.2.11...3.0.1
This switches the library to 0.8 and therefore suppresses various warnings arising from its use of 0.7 previously (around `COMMAND` vs `FUNCTION`).
The `RUN_WITH_CACHE` function has been removed, the replacement is to use `SET_CACHE_MOUNTS_ENV` then `RUN --mount`.
=> Earthfile: Bump to rust lib 3.0.1

wolfssl-sys/wrapper.h, wolfssl/src/chacha20_poly1305.rs, wolfssl/src/context.rs, wolfssl/src/lib.rs, wolfssl/src/ssl.rs
Add api's for calling `wolfSSL_set_verify` and `wolfSSL_CTX_set_verify` methods. For simplicity, set the last `VerifyMethod` callback parameter in both the apis as None. We can add it in future if requires.
=> Add support for `wolfSSL_set_verify` methods

wolfssl/src/context.rs, wolfssl/src/error.rs, wolfssl/src/lib.rs
Add abstraction `FatalErrorKind` over wolfssl error code and add a public api for retrieving it
=> CVPN-753: Add public api for retrieving ErrorKind

Earthfile, wolfssl/Cargo.toml, wolfssl/src/lib.rs
... default enabled, but this allows omitting the liboqs dependency chain if desired.
To ensure the build works we lint both with all features and with no features.
=> wolfssl: Expose postquantum as a cargo feature

Cargo.lock, README.md, wolfssl-sys/Cargo.toml, wolfssl/Cargo.toml
This PR will release wolfssl-sys to version v1.0.0, as well as update the release documentation.
The cargo documentation [1] is slightly misleading. It was understood that when both the path and the version are specified for a crate, the version attribute will be ignored when not publishing, but in fact it is not ignored. After re-reading the docs, its behaviour is:
During local/ci:
- Cargo will follow the path to locate the crate
- After the crate is located, the crate's version will be validated against the one specified
During publish:
- Cargo will only refer to the version in crates.io
Due to this updated understanding, we need to change our release instruction to update both the `wolfssl-sys` crate version and the version specified under the dependencies in the `wolfssl` crate.
[1]: …
=> CVPN-249 Release wolfssl-sys v1.0.0

Cargo.lock, wolfssl/Cargo.toml, wolfssl/src/callback.rs, wolfssl/src/ssl.rs, wolfssl/tests/ping_pong.rs
Instead take `&mut self` in `Session`'s methods, this allows the consumers to choose to use an `&mut` session themselves and avoid locking, but does not preclude them using a `Mutex` themselves.
With this we now know that there can be no parallel code paths which might hit an `IOCallback` method, therefore we can make those receive `&mut self` (since the callback type is owned by the session).
Together with the use of `&mut self` in the various `Session` methods this now makes `io_cb_mut()` usable by consuming applications to access their IOCallback implementation's state knowing that nothing else can be touching it.
=> Remove the `Mutex` from `WolfsslPointer` in `Session::ssl`

.github/workflows/ci.yaml, .github/workflows/release.yaml
... this avoids rate-limiting.
=> GHA: Pass GH token to `earthly/actions-setup`

.github/actions/check-dependencies/action.yml, .github/workflows/release.yaml, README.md
When releasing `wolfssl` from `main` we want to be sure it depends on the most recent `wolfssl-sys` changes in `main`.
For usage from git this is fine since the dependency involves a `path` key. This is also what we actually test in CI.
For usage from crates.io this means we want the `version` field to point to the latest version of the code -- which may mean we need to release `wolfssl-sys` first if there are unreleased changes there.
The SHA of the tree object of the `wolfssl-sys` subtree changes precisely when `wolfssl-sys` is changed, so we can match using that by comparing main to the tagged release.
There are four states:
* `released`: `wolfssl` depends on a release of `wolfssl-sys` which contains the most recent code -> go ahead and release
* `out-of-date`: `wolfssl` depends on a …
=> GHA: Coordinate wolfssl and wolfssl-sys releases

.github/CODEOWNERS, wolfssl-sys/Cargo.toml, wolfssl/Cargo.toml
This releases the changes from #142 as well as being the first time we will excercise the release machinery after #147.
I also took the opportunity to refresh CODEOWNERS and the author fields in the crates.
=> Release `wolfssl-sys` v1.1.0

.github/workflows/release.yaml, Cargo.lock
#148 and #150 missed updating `Cargo.lock` do so and add a CI step so it cannot be forgotten in the future
=> Release with fresh `Cargo.lock`

README.md
Also make it clearer that if there are no wolfssl-sys changes (state is `released` already) then wolfssl can be released by itself.
---
[Rendered](https://github.com/expressvpn/wolfssl-rs/blob/afa35c4f904a1f02c0cc297b9cbb9beb2b71edc7/README.md#releasing)
=> README: Add diagram to clarify release flow.

wolfssl-sys/Cargo.toml
This reduces the size of the .rlib file by 2 MB in release. Tested with the earthly +build-release.
One thing though, I don't think we even use dilithium or falcon at this stage but lightway-core includes them. So I'll leave it in for now.
=> build: only include oqs features we use

wolfssl-sys/build.rs
ASM optimisations can be enabled only in arm and x86_64 builds. It does not support x86.
Ref:
https://www.wolfssl.com/documentation/manuals/wolfssl/chapter02.html#-enable-sp-asm
=> wolfssl-sys: disable asm optimizations for x86 builds

wolfssl/src/context.rs, wolfssl/src/lib.rs, wolfssl/src/ssl.rs, wolfssl/tests/ping_pong.rs
The `Protocol` type corresponds to a request to WolfSSL at setup time to take on a particular role (client vs server) supporting some set of versions (DTLS, TLS, 1.x etc). Accordingly it contains some "umbrella" versions such as
`DtlsClient` and `TlsServer` which request only "some version of" the respective protocols.
Therefore it does not make sense to ask "is this protocol DTLS 1.3 etc" since that would be false for `DtlsClient` even though the protocol which has actually been negotiated may well be version 1.3.
Move the helper methods to the `ProtocolVersion` type which reflects the runtime negotiated actual version and make use of `Session::version()` in the places which previously used the `protocol` field (which is now unneeded).
After having done this rename `Protocol` to `Method` …
=> Use correct *runtime* checks for (D)TLS 1.3

.github/workflows/ci.yaml
This is required to have it actually block merging PRs if one of the constituent jobs fails, since such a failure will mark the `ci` job as "skipped" which does not block merging.
See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
=> GHA: Ensure that the CI nexus job fails if any dependent job fails

wolfssl-sys/build.rs
TLS1.3 Middlebox Compatibility (RFC8446 Appendix D.4) has been documented to help some TLS connections more reliably traverse some networks.
Ref: https://datatracker.ietf.org/doc/html/rfc8446#appendix-D.4
=> wolfssl-sys: Enable TLS1.3 Middlebox Compatibility

wolfssl/src/error.rs
Exposing this presumably unhandlable error for application to restart connection as soon as possible.
=> wolfssl: Expose Duplicate Message Error

wolfssl/Cargo.toml, wolfssl/src/context.rs, wolfssl/src/lib.rs, wolfssl/src/ssl.rs
This adds `unsafe_op_in_unsafe_fn` and `unused_unsafe` from rustc plus `multiple_unsafe_ops_per_block`, `undocumented_unsafe_blocks` and `unnecessary_safety_comment` to the wolfssl crate.
This forces us to be more robust in our safety comments, in particular `unsafe_op_in_unsafe_fn` and `multiple_unsafe_ops_per_block` are good practice to ensure that every unsafe operation has a corresponding safety comment.
=> Enable some additional rustc clippy lints for unsafe code

wolfssl-sys/Cargo.toml, wolfssl-sys/build.rs, wolfssl-sys/patches/disable-falcon-dilithium.patch
We disable falcon and dilithium as we are currently not using either of these schemes. This reduces the size of our library significantly.
=> wolfssl: patch out unused falcon and dilithium

wolfssl-sys/build.rs, wolfssl-sys/patches/disable-falcon-dilithium.patch
Moving from v5.6.6-stable we are picking up:
* https://github.com/wolfSSL/wolfssl/releases/tag/v5.7.0-stable
* https://github.com/wolfSSL/wolfssl/releases/tag/v5.7.2-stable
(there was no 5.7.1)
Our `disable-falcon-dilithium.patch` required an update, likely due to the changes in https://github.com/wolfSSL/wolfssl/pull/7622.
=> Update to wolfssl 5.7.2

wolfssl-sys/examples/connect_pq.rs, wolfssl-sys/src/bindings.rs, wolfssl-sys/src/lib.rs, wolfssl-sys/wrapper.h, wolfssl/src/context.rs, wolfssl/src/error.rs, wolfssl/src/lib.rs, wolfssl/src/ssl.rs
Moving from v5.7.2-stable
We are picking up:
https://github.com/wolfSSL/wolfssl/releases/tag/v5.7.4-stable
Updated to implement an important bugfix:
https://github.com/wolfSSL/wolfssl/pull/8084
=> CVPN-1521 Update to upstream wolfssl to 5.7.4

wolfssl/tests/ping_pong.rs
```
error: missing documentation for the crate
--> wolfssl/tests/ping_pong.rs:1:1
|
1   | / #![deny(unsafe_code)] // unsafety should all be in the library.
2   | |
3   | | #[cfg(feature = "debug")]
4   | | use wolfssl::Tls13SecretCallbacks;
...   |
268 | |     tokio::join!(client, server);
269 | | }
| |_^
|
= note: requested on the command line with `-D missing-docs`
```
---
https://github.com/expressvpn/wolfssl-rs/pull/198 is waiting for https://github.com/docker-library/official-images/pull/17990 so CI will pass. In the meantime address the new lints discovered by running locally.
=> Address new clippy lint in Rust 1.83

wolfssl-sys/build.rs, wolfssl-sys/patches/revert-aarch64-poly1305-asm-improve-performance.patch
This patch reverts https://github.com/wolfSSL/wolfssl/pull/7859 PR as WolfSSL 5.7.4 currently breaks ChaCha20 TCP connection from an Apple M1 Client in one of our coverage test in our lightway-core library. It turns out the PR causes "MAC did not match" in the server-side, which means the tag (used for authenticating the cipher-text) generated in the client-side is incorrect.
This new patch has already been applied to `lightway-core` library as well since this issue is occuring in WolfSSL 5.7.4 release.
=> Revert WolfSSL Poly1305 PR 

.github/workflows/nightly-cargo-deny.yaml
Cargo deny CI started throwing errors recently after rust 1.83.0 upgrade:
https://github.com/expressvpn/wolfssl-rs/actions/runs/12139835174/job/33848300194
Error:
```
2024-12-03 12:39:37 [ERROR] failed to fetch crates: warning: /github/workspace/wolfssl/Cargo.toml: unused manifest key `lints` (may be supported in a future version)
this Cargo does not support nightly features, but if you
switch to nightly channel you can pass
`-Zlints` to enable this feature.
error: failed to parse lock file at: /github/workspace/Cargo.lock
2024-12-03 12:39:37 [ERROR] failed to fetch crates: warning: /github/workspace/wolfssl/Cargo.toml: unused manifest key `lints` (may be supported in a future version)
```
Updated the github action version which has the fix for rust 1.83.0: …
=> Fix cargo deny CI failure

wolfssl/src/lib.rs, wolfssl/src/ssl.rs
The upstream documentation is not covering every possible error (e.g. we see `SOCKET_ERROR_E` from various functions which do not document it).
Be more conservative and turn such errors into an `Err` return instead of panicing via `unreachable!()`.
=> Reduce use of `unreachable!(...)`

wolfssl-sys/build.rs, wolfssl-sys/patches/fix-kyber-prf-non-avx2.patch
The patch is from:
https://github.com/wolfSSL/wolfssl/pull/8306
This patch fixes an issue where older CPUs, with no AVX2 support, fail to handshake Kyber/ML-KEM.
=> CVPN-1681 Fix failed Kyber/ML-KEM handshake with non-AVX2 CPU

.github/workflows/ci.yaml, Earthfile, wolfssl-sys/build.rs
Build WolfSSL on the iOS/tvOS platform with similar build flags from lightway-core. We would need to set `TVOS_DEPLOYMENT_TARGET` or `IPHONEOS_DEPLOYMENT_TARGET` in the environment variable as well in the cargo config, as it is needed to make sure we support older iOS version as well
We would need to build the tvOS with nightly feature (-Zbuild-std) as `aarch64-apple-tvos` is a tier 3 target and does not support building host tools.
Build flag for iOS:
```
[wolfssl-sys 2.0.0]    * System type:                apple-ios
[wolfssl-sys 2.0.0]    * Host CPU:                   aarch64
[wolfssl-sys 2.0.0]    * C Compiler:                 clang
[wolfssl-sys 2.0.0]    * C Flags:                    -O3 -fPIC --target=arm64-apple-ios -miphoneos-version-min=15.0 -isysroot …
```
=> CVPN-1846 Build WolfSSL on iOS/tvOS

.github/workflows/ci.yaml, wolfssl-sys/build.rs
Add new targets on rustup, and tweak some build flags as well for x86_64 iOS simulator.
New build flags:
```
* System type:                apple-darwin
[wolfssl-sys 2.0.0]    * Host CPU:                   x86_64
[wolfssl-sys 2.0.0]    * C Compiler:                 clang
[wolfssl-sys 2.0.0]    * C Flags:                    -O3 -fPIC -m64 --target=x86_64-apple-ios-simulator -mios-simulator-version-min=15.0 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk  -g -fPIC -DWOLFSSL_DTLS_ALLOW_FUTURE -DWOLFSSL_MIN_RSA_BITS=2048 -DWOLFSSL_MIN_ECC_BITS=256 -DUSE_CERT_BUFFERS_4096 -DUSE_CERT_BUFFERS_256 -DWOLFSSL_NO_SPHINCS -DWOLFSSL_TLS13_MIDDLEBOX_COMPAT -O3 -D_FORTIFY_SOURCE=2   -Wno-pragmas -Wall -Wextra …
```
=> Support building WolfSSL on iOS x86_64 simulator as well

.github/workflows/ci.yaml, wolfssl-sys/build.rs
Add support for x86_64 tvOS simulator
Also optimise the CI to use https://github.com/marketplace/actions/rustup-toolchain-install for better clarity
=> wolfssl-sys: support building on x86_64 tvOS simulator

.github/workflows/ci.yaml
Checkout submodules as well when we are using github action's checkout to save time fetching from WolfSSL's repo.
Reference: https://github.com/marketplace/actions/checkout
=> ci: checkout submodules to save time

wolfssl-sys/src/bindings.rs, wolfssl/src/error.rs
Add new error variant PeerClosed when the peer sends close notify alert.
WolfSsl uses two errors for same error (ref below), just follow the same.
Ref:
https://github.com/wolfSSL/wolfssl/blob/c29fba5b7ed912bb62e6bc6bd2e87562fd16ad3e/src/internal.c#L26439-L26441
=> Add new error variant PeerClosed

.github/workflows/ci.yaml, .github/workflows/nightly-rust-update-check.yaml
Update GitHub bot to auto-update RUST_VERSION in github action as well to be in-sync with Earthfile
=> ci: auto update Rust version in GitHub action

wolfssl/src/context.rs
Just a small change — otherwise method chaining in `ContextBuilder` is not complete.
=> fix `with_verify_method` to return self for method chaining

wolfssl-sys/build.rs, wolfssl-sys/patches/CVPN-1945-Lower-max-mtu-for-DTLS-1.3-handshake-message.patch
During the DTLS 1.3 handshake, large post-quantum certificates are exchanged. While DTLS supports message fragmentation, the first packet in the exchange remains extremely close to the MTU limit—just 15 bytes of headroom in the worst-case scenario (e.g., PPPoE or PPPoA networks). This minimal buffer leads to fragmentation on many networks despite the use of handshake fragmentation.
We observed that the current fragmentation behavior splits packets in a ~95/5 ratio, resulting in a large first packet and a tiny second one. This causes the first packet to be fragmented anyway, defeating the purpose of the feature.
This patch modifies the `Dtls13SendFragmentedInternal()` function in `dtls13.c` to reduce the maximum fragment size by 500 bytes:
```c
maxFragment = wolfSSL_GetMaxFragSize(ssl, …
```
=> Lower max MTU for DTLS 1.3 handshake messages to prevent fragmentation with large certificates

wolfssl-sys/build.rs
According to the docs, the marco "SP_INT_BITS" determines the number of bits in sp_int, which is the largest bignum that can be handled. https://www.wolfssl.com/documentation/manuals/wolfssl/chapter02.html#sp_int_bits
By default it is 3072. Since we are using 4096 bits keys, we need to add the c flag "-DSP_INT_BITS=4096" override the marco and support 4096 bits keys.
=> wolfssl: "INIT_MP_INT_SIZE failed" fix on ARM32

wolfssl-sys/Cargo.toml, wolfssl-sys/build.rs, wolfssl/Cargo.toml, wolfssl/src/context.rs
Add an optional feature where wolfssl will be compiled with enable-sys-ca-certs such that it can load trusted certificates from the system's trust store.
Even with this feature on, unless the wolfssl context has called wolfSSL_CTX_load_system_CA_certs, the system's certs will not be loaded.
=> CVPN-2123 Add Feature `system-ca-certs`

.github/workflows/ci.yaml, wolfssl-sys/build.rs
Compile with WOLFSSL_APPLE_NATIVE_CERT_VALIDATION when system_ca_certs feature is on: https://www.wolfssl.com/wolfssl-extends-support-for-system-ca-certificates-to-apple-devices/
=> ca-cert: Compile library with WOLFSSL_APPLE_NATIVE_CERT_VALIDATION

wolfssl/src/aes256.rs
Having both encrpytion and decryption aes crpyto instance in a single struct
seems more restrictive. Since encrypt and decrypt apis take &mut self, we cannot do encrypt and decrypt parallely.
This restriction is artificially introduced and unnecessary.
Avoid it by making `Aes256Gcm` struct only to manage one crypto instance.
End user application can manage two instances of `Aes256Gcm` for encrpytion and decryption if required to do parallely.
=> WolfSsl: Aes256gcm handle one crypto instance

.github/workflows/release.yaml, Earthfile
Until now, we use gh-find-current-pr to find the PR number of thespecified commit. This was needed when the action is triggered from main branch push event, since we do not know the PR number from context.
This also works fine for pull requests from branches created in main repo. But it is failing for forked repos.
Example (logs may be purged in future):
https://github.com/expressvpn/wolfssl-rs/actions/runs/16980030164/job/48137907811
To overcome this issue, use `github.event.number` for pull request event and use the one from above action if it is push event.
=> Fix release CI failing from forked repos

wolfssl-sys/build.rs
Previously we skipped copying the .git directory/file in this commit:
https://github.com/expressvpn/wolfssl-rs/pull/286/commits/ead8c149be04cfb3da1f79e6fc9aab9c230a706d
to allow git patch in windows.
When testing in local environment, wolfssl-src is a submodule,
so `.git` will be a file and this works fine with recompilation.
But while building as a dependency (ex: lightway), wolfssl-src will be a directory.
And this breaks CI, since `if check` order is wrong and .git
directory is being copied unintentionally to the build folder
throwing the following error:
```
[wolfssl-sys 2.0.0] cargo:rerun-if-changed=wolfssl-src
[wolfssl-sys 2.0.0] Error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[wolfssl-sys 2.0.0] Error while copying dir …
```
=> wolfssl-sys: fix skip copying .git dir while building
